export const accountingSoftware = [
	'quickbooks-online',
	'ms-dynamics',
	'xero',
	'myob',
	'quickbooks-enterprise',
	'wave',
	'quickbooks-premier',
	'acumatica',
	'maxwell',
	'sap',
	'exact-macola',
	'cougar-mountain',
	'sage-intacct',
	'oracle',
	'peachtree',
	'adagio',
	'accpac',
	'accountedge',
	'quickbooks-desktop',
	'sage-50',
	'excel',
	'omega',
	'netsuite',
	'mas-200',
	'mas-90',
	'business-works',
	'great-plains',
	'freeagent',
	'quickbooks-pro',
	'traverse',
	'microsoft-access',
	'daceasy',
	'epicor',
	'reckon',
	'freshbooks',
	'gnu-cash',
	'mas-500',
	'financialforce',
	'timberline',
	'simply-accounting',
	'master-builder',
	'kashflow',
	'sage-300',
	'sage-100'
] as const;

export const supportedSoftware = [
	'quickbooks-online',
	'xero',
	'myob',
	'quickbooks-enterprise',
	'wave',
	'quickbooks-premier',
	'freshbooks'
] as const;
